### ISSUE TITLE
PMF vs. free energy curve

### ISSUE THREAD

**Issue by agrossfield** [DanielMarkthaler/PMF_Artifacts_LessonsLearned_LiveCoMS#1]
This probably a bit nit-picky of me, but strictly speaking umbrella sampling does not produce a PMF, but rather a free energy curve.  A free energy curve has the Jacobian contributions included, while a PMF does not.  A good way to think about it is:

PMF <-> probability density
free energy curve <-> probability

To be clear, the authors clearly know this -- they talk extensively about the role of the Jacobian. I'm complaining about nomenclature, not the substance of the article (which looks fantastic on my first read-through).  The field tends to use the 2 terms as if they're equivalent, which drives me nuts.  As far as I can tell, the only method that actually produces a PMF is ABF -- everything else works on probability, and so produces a free energy curve.

Cheers,

Alan

**Comment by DanielMarkthaler** [comment]
Thanks a lot for the comment! 
We corrected the nomenclature in the revised / release version of the manuscript.
Best,
Daniel
